### ISSUE TITLE
Eoe10 not showing up on the Raidbrowser

### ISSUE THREAD

**Issue by Yzeyr** [Ostoic/RaidBrowser#12]
"LFM eoe10 need 1 tank & dps - /w gs & achievement. - boe res" 

This message does not show up on the raidbrowser.

**Comment by Ostoic** [comment]
Fixed in [this](https://github.com/Ostoic/RaidBrowser/commit/14dfbeaa034d257e8e61aa0c902515e0197e6eab) commit.
