### ISSUE TITLE
Raidbrowser problem

### ISSUE THREAD

**Issue by boogY11** [Ostoic/RaidBrowser#33]
In the raidbrowser tab when i hover the raid message it doesnt show the additional text. pls help
![image](https://user-images.githubusercontent.com/124068951/215803157-ad3b7179-b260-4fb2-8a2c-58e99e674368.png)

**Comment by MassCraxx** [comment]
Did you try the latest version? Something like this just got fixed.

**Comment by boogY11** [comment]
yes its working now, thx
