### ISSUE TITLE
Issue with Join message

### ISSUE THREAD

**Issue by Hasamida** [Ostoic/RaidBrowser#34]
The "Join" button nor double clicking does not seem to be working for me. I have tried with the Active and specific spec settings on multiple characters.
Contrary to the screenshots in the ReadMe section the addon does not even recognise any GS when saving a spec. I am suspecting my gearscore addon not being compatible

![Wow_2023-02-05_11-21-35](https://user-images.githubusercontent.com/124497008/216813536-756d6886-651a-4e40-a3d3-db24e2c0f957.png)

**Comment by Ostoic** [comment]
I had a friend run into this problem while setting up their new ElvUI interface. I told them to download Gearscore (since they didn't have it) and that fixed it. However, I believe it shouldn't silently fail like that and would just not provide your gearscore in the join message.  Are you using a particular version of the common Gearscore addon, or a different one?

**Comment by Hasamida** [comment]
I think its a comomn one

![Wow_2023-02-11_14-40-06](https://user-images.githubusercontent.com/124497008/218261128-a71a1c31-3e34-49cf-8d11-f5f909ea2999.png)

**Comment by Hasamida** [comment]
I've noticed i had escript errors turned off. I am getting the following error when clicking on the join button

Message: Interface\AddOns\RaidBrowser\stats.lua:166: attempt to concatenate local 'gs' (a nil value)
Time: 02/11/23 14:54:58
Count: 1
Stack: (tail call): ?
Interface\AddOns\Auctionator\AtrErrorInspector.lua:106: in function <Interface\AddOns\Auctionator\AtrErrorInspector.lua:51>
[C]: ?
Interface\AddOns\RaidBrowser\stats.lua:166: in function `build_inv_string'
Interface\AddOns\RaidBrowser\gui.lua:68: in function <Interface\AddOns\RaidBrowser\gui.lua:63>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1



I am also getting alot of errors regarding BonusScaner which from my understanding is part of GearScore

**Comment by Hasamida** [comment]
Today i am getting different set of errors:

`Message: Interface\AddOns\RaidBrowser\raidset_frame.lua:105: attempt to concatenate local 'gs' (a nil value)
Time: 02/12/23 13:10:07
Count: 1
Stack: Interface\AddOns\Auctionator\AtrErrorInspector.lua:106: in function <Interface\AddOns\Auctionator\AtrErrorInspector.lua:51>
[C]: ?
Interface\AddOns\RaidBrowser\raidset_frame.lua:105: in function <Interface\AddOns\RaidBrowser\raidset_frame.lua:96>

Locals: msg = " Interface\AddOns\RaidBrowser\raidset_frame.lua:105: attempt to concatenate local 'gs' (a nil value)"
funcnames = <table> {
}
funcstr = ""
looksLikeAuctionatorError = false
inAtrErrorHandler = true
origErrorHandler = <function> defined Interface\FrameXML\BasicControls.xml:<Scripts>:4
zc = <table> {
 msg_red = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:609
 IsEnglishLocale = <function> defined @Interface\AddOns\Auctionator\AuctionatorLocalize.lua:52
 msg = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:738
 GetArrayElemOrFirst = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:150
 NumToBool = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:563
 CopyDeep = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1004
 tallyAdd = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1122
 ShowHide = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:36
 StringStartsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:931
 msg_color = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:615
 round = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:603
 printmem = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1032
 StringContains = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:893
 CheckDeferredCall = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:332
 priceToMoneyString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:842
 tallyPrint = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1134
 msg_badErr = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:645
 GetArrayElemOrNil = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:165
 BoolToNum = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:553
 If = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:99
 periodic = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:355
 Min = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:69
 msg_pink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:610
 SetTextIf = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:47
 TrimBrackets = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:975
 msg_str = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:628
 ItemNamefromLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:472
 enc64 = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:215
 Val = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:58
 TrimQuotes = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:955
 StringEndsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:911
 printableLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1019
 PrintTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:385
 StringSame = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:875
 priceToString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:806
 PullItemIntoMemory = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:521
 val2gsc = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:788
 PrintKeysSorted = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:110
 msg_ex = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:747
 Negate = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:573
 ClearTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:995
 BoolToString = <function> define`


I have disabled it at the error now look like this:

`Message: Interface\AddOns\RaidBrowser\raidset_frame.lua:105: attempt to concatenate local 'gs' (a nil value)
Time: 02/12/23 13:13:20
Count: 2
Stack: [C]: ?
Interface\AddOns\RaidBrowser\raidset_frame.lua:105: in function <Interface\AddOns\RaidBrowser\raidset_frame.lua:96>

Locals: `

**Comment by MassCraxx** [comment]
Had the same problem using and older Gearscore (non-Lite) version. Should be fixed with #39.

Feel free to test out the fixed version (alongside some other fixes) here: https://github.com/MassCraxx/RaidBrowser/tree/dev

**Comment by Hasamida** [comment]
It seems to be fixed. It loaded the GS and the join message was sent, but it doesnt display anything in the selection window. Might be that the spec name is too long.

![image](https://user-images.githubusercontent.com/124497008/218518981-a933196a-5841-46f4-9268-ebc51b5eaca1.png)


![image](https://user-images.githubusercontent.com/124497008/218518898-5913941e-2f36-4db4-8603-635865d97532.png)

**Comment by MassCraxx** [comment]
Yes, this is a (minor) bug, will be fixed by #27 but its not included in my dev branch, as this is not my fix.
Lets hope the @Ostoic finds some time soon to deal with all this =)

**Comment by Ostoic** [comment]
I'll close this for now and open a new issue for the spec name not showing up in the combo box.
